-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 20:41:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema grupo-investigacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema grupo-investigacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `grupo-investigacion` DEFAULT CHARACTER SET utf8mb4 ;
USE `grupo-investigacion` ;

-- -----------------------------------------------------
-- Table `grupo-investigacion`.`dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`dependencia` (
  `id_dependencia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dependencia`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`integrantes` (
  `id_integrante` INT NOT NULL AUTO_INCREMENT,
  `grado` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `id_dependencia` INT NOT NULL,
  `perfil` MEDIUMTEXT NOT NULL,
  `informacion_academica` MEDIUMTEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(15) NOT NULL,
  `ubicacion` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_integrante`),
  INDEX `fk_integrantes_dependencia1_idx` (`id_dependencia` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `fk_integrantes_dependencia1`
    FOREIGN KEY (`id_dependencia`)
    REFERENCES `grupo-investigacion`.`dependencia` (`id_dependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`anios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`anios` (
  `id_anio` INT NOT NULL,
  `anio` INT NOT NULL,
  PRIMARY KEY (`id_anio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`programas_educativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`programas_educativos` (
  `id_programa_educativo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_programa_educativo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actividad_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actividad_docente` (
  `id_actividad_docente` INT NOT NULL AUTO_INCREMENT,
  `id_programa_educativo` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_actividad_docente`),
  INDEX `fk_actividad_docente_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_actividad_docente_anios1_idx` (`id_anio` ASC) VISIBLE,
  INDEX `fk_actividad_docente_programas_educativos1_idx` (`id_programa_educativo` ASC) VISIBLE,
  CONSTRAINT `fk_actividad_docente_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_docente_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_docente_programas_educativos1`
    FOREIGN KEY (`id_programa_educativo`)
    REFERENCES `grupo-investigacion`.`programas_educativos` (`id_programa_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`materias` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`id_materia`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`lineas` (
  `id_linea` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_linea`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`tipos_tutelaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`tipos_tutelaje` (
  `id_tipo_tutelaje` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_tipo_tutelaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actividades_tutelaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actividades_tutelaje` (
  `id_actividad_tutelaje` INT NOT NULL AUTO_INCREMENT,
  `alumno` INT NOT NULL,
  `id_programa_educativo` INT NOT NULL,
  `id_tipo_tutelaje` INT NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `id_integrante` INT NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_actividad_tutelaje`),
  INDEX `fk_actividades_tutelaje_programas_educativos1_idx` (`id_programa_educativo` ASC) VISIBLE,
  INDEX `fk_actividades_tutelaje_tipos_tutelaje1_idx` (`id_tipo_tutelaje` ASC) VISIBLE,
  INDEX `fk_actividades_tutelaje_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_actividades_tutelaje_anios1_idx` (`id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_tutelaje_programas_educativos1`
    FOREIGN KEY (`id_programa_educativo`)
    REFERENCES `grupo-investigacion`.`programas_educativos` (`id_programa_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_tutelaje_tipos_tutelaje1`
    FOREIGN KEY (`id_tipo_tutelaje`)
    REFERENCES `grupo-investigacion`.`tipos_tutelaje` (`id_tipo_tutelaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_tutelaje_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_tutelaje_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actividad_docente_has_lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actividad_docente_has_lineas` (
  `id_actividad_linea` INT NOT NULL AUTO_INCREMENT,
  `id_actividad_docente` INT NOT NULL,
  `id_linea` INT NOT NULL,
  PRIMARY KEY (`id_actividad_linea`, `id_actividad_docente`, `id_linea`),
  INDEX `fk_actividad_docente_has_lineas_lineas1_idx` (`id_linea` ASC) VISIBLE,
  INDEX `fk_actividad_docente_has_lineas_actividad_docente1_idx` (`id_actividad_docente` ASC) VISIBLE,
  CONSTRAINT `fk_actividad_docente_has_lineas_actividad_docente1`
    FOREIGN KEY (`id_actividad_docente`)
    REFERENCES `grupo-investigacion`.`actividad_docente` (`id_actividad_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_docente_has_lineas_lineas1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `grupo-investigacion`.`lineas` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`areas_academicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`areas_academicas` (
  `id_area_academica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area_academica`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`grados_academicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`grados_academicos` (
  `id_grado_academico` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_grado_academico`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`integrantes_has_grados_academicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`integrantes_has_grados_academicos` (
  `id_integrante_grado` INT NOT NULL AUTO_INCREMENT,
  `id_integrante` INT NOT NULL,
  `id_grado_academico` INT NOT NULL,
  PRIMARY KEY (`id_integrante_grado`, `id_integrante`, `id_grado_academico`),
  INDEX `fk_integrantes_has_grados_academicos_grados_academicos1_idx` (`id_grado_academico` ASC) VISIBLE,
  INDEX `fk_integrantes_has_grados_academicos_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  CONSTRAINT `fk_integrantes_has_grados_academicos_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_integrantes_has_grados_academicos_grados_academicos1`
    FOREIGN KEY (`id_grado_academico`)
    REFERENCES `grupo-investigacion`.`grados_academicos` (`id_grado_academico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`areas_interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`areas_interes` (
  `id_area_interes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_area_interes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`integrantes_has_areas_interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`integrantes_has_areas_interes` (
  `id_integrante_area` INT NOT NULL AUTO_INCREMENT,
  `id_integrante` INT NOT NULL,
  `id_area_interes` INT NOT NULL,
  PRIMARY KEY (`id_integrante_area`, `id_integrante`, `id_area_interes`),
  INDEX `fk_integrantes_has_areas_interes_areas_interes1_idx` (`id_area_interes` ASC) VISIBLE,
  INDEX `fk_integrantes_has_areas_interes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  CONSTRAINT `fk_integrantes_has_areas_interes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_integrantes_has_areas_interes_areas_interes1`
    FOREIGN KEY (`id_area_interes`)
    REFERENCES `grupo-investigacion`.`areas_interes` (`id_area_interes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actividades_tutelaje_has_lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actividades_tutelaje_has_lineas` (
  `id_actividad_linea` INT NOT NULL AUTO_INCREMENT,
  `id_actividad_tutelaje` INT NOT NULL,
  `id_linea` INT NOT NULL,
  PRIMARY KEY (`id_actividad_linea`, `id_actividad_tutelaje`, `id_linea`),
  INDEX `fk_actividades_tutelaje_has_lineas_lineas1_idx` (`id_linea` ASC) VISIBLE,
  INDEX `fk_actividades_tutelaje_has_lineas_actividades_tutelaje1_idx` (`id_actividad_tutelaje` ASC) VISIBLE,
  CONSTRAINT `fk_actividades_tutelaje_has_lineas_actividades_tutelaje1`
    FOREIGN KEY (`id_actividad_tutelaje`)
    REFERENCES `grupo-investigacion`.`actividades_tutelaje` (`id_actividad_tutelaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividades_tutelaje_has_lineas_lineas1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `grupo-investigacion`.`lineas` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`fuentes_financiamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`fuentes_financiamiento` (
  `id_fuente_financiamiento` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_fuente_financiamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`proyectos_desarrollados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`proyectos_desarrollados` (
  `id_proyecto_desarrollado` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `id_fuente_financiamiento` INT NOT NULL,
  `fecha_fin` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_proyecto_desarrollado`),
  INDEX `fk_proyectos_desarrollados_anios1_idx` (`id_anio` ASC) VISIBLE,
  INDEX `fk_proyectos_desarrollados_fuentes_financiamiento1_idx` (`id_fuente_financiamiento` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_desarrollados_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_desarrollados_fuentes_financiamiento1`
    FOREIGN KEY (`id_fuente_financiamiento`)
    REFERENCES `grupo-investigacion`.`fuentes_financiamiento` (`id_fuente_financiamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`proyectos_desarrollados_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`proyectos_desarrollados_has_integrantes` (
  `id_proyecto_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto_desarrollado` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_proyecto_integrante`, `id_proyecto_desarrollado`, `id_integrante`),
  INDEX `fk_proyectos_desarrollados_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_proyectos_desarrollados_has_integrantes_proyectos_desarr_idx` (`id_proyecto_desarrollado` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_desarrollados_has_integrantes_proyectos_desarrol1`
    FOREIGN KEY (`id_proyecto_desarrollado`)
    REFERENCES `grupo-investigacion`.`proyectos_desarrollados` (`id_proyecto_desarrollado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_desarrollados_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`proyectos_desarrollados_has_lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`proyectos_desarrollados_has_lineas` (
  `id_proyecto_linea` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto_desarrollado` INT NOT NULL,
  `id_linea` INT NOT NULL,
  PRIMARY KEY (`id_proyecto_linea`, `id_proyecto_desarrollado`, `id_linea`),
  INDEX `fk_proyectos_desarrollados_has_lineas_lineas1_idx` (`id_linea` ASC) VISIBLE,
  INDEX `fk_proyectos_desarrollados_has_lineas_proyectos_desarrollad_idx` (`id_proyecto_desarrollado` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_desarrollados_has_lineas_proyectos_desarrollados1`
    FOREIGN KEY (`id_proyecto_desarrollado`)
    REFERENCES `grupo-investigacion`.`proyectos_desarrollados` (`id_proyecto_desarrollado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_desarrollados_has_lineas_lineas1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `grupo-investigacion`.`lineas` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`tipos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`tipos_productos` (
  `id_tipo_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`productos_cientificos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`productos_cientificos` (
  `id_producto_cientifico` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_producto` INT NOT NULL,
  `titulo` VARCHAR(70) NOT NULL,
  `lugar` VARCHAR(255) NOT NULL,
  `fecha` DATE NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_producto_cientifico`),
  INDEX `fk_productos_cientificos_tipos_productos1_idx` (`id_tipo_producto` ASC) VISIBLE,
  INDEX `fk_productos_cientificos_anios1_idx` (`id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_productos_cientificos_tipos_productos1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `grupo-investigacion`.`tipos_productos` (`id_tipo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_cientificos_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`productos_cientificos_has_lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`productos_cientificos_has_lineas` (
  `id_producto_linea` INT NOT NULL AUTO_INCREMENT,
  `id_producto_cientifico` INT NOT NULL,
  `id_linea` INT NOT NULL,
  PRIMARY KEY (`id_producto_linea`, `id_producto_cientifico`, `id_linea`),
  INDEX `fk_productos_cientificos_has_lineas_lineas1_idx` (`id_linea` ASC) VISIBLE,
  INDEX `fk_productos_cientificos_has_lineas_productos_cientificos1_idx` (`id_producto_cientifico` ASC) VISIBLE,
  CONSTRAINT `fk_productos_cientificos_has_lineas_productos_cientificos1`
    FOREIGN KEY (`id_producto_cientifico`)
    REFERENCES `grupo-investigacion`.`productos_cientificos` (`id_producto_cientifico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_cientificos_has_lineas_lineas1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `grupo-investigacion`.`lineas` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`productos_cientificos_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`productos_cientificos_has_integrantes` (
  `id_producto_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_producto_cientifico` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_producto_integrante`, `id_producto_cientifico`, `id_integrante`),
  INDEX `fk_productos_cientificos_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_productos_cientificos_has_integrantes_productos_cientifi_idx` (`id_producto_cientifico` ASC) VISIBLE,
  CONSTRAINT `fk_productos_cientificos_has_integrantes_productos_cientificos1`
    FOREIGN KEY (`id_producto_cientifico`)
    REFERENCES `grupo-investigacion`.`productos_cientificos` (`id_producto_cientifico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_cientificos_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`proyectos_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`proyectos_estudiantes` (
  `id_proyecto_estudiante` INT NOT NULL AUTO_INCREMENT,
  `id_programa_educativo` INT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_proyecto_estudiante`),
  INDEX `fk_proyectos_estudiantes_anios1_idx` (`id_anio` ASC) VISIBLE,
  INDEX `fk_proyectos_estudiantes_programas_educativos1_idx` (`id_programa_educativo` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_estudiantes_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_estudiantes_programas_educativos1`
    FOREIGN KEY (`id_programa_educativo`)
    REFERENCES `grupo-investigacion`.`programas_educativos` (`id_programa_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`proyectos_estudiantes_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`proyectos_estudiantes_has_integrantes` (
  `id_proyecto_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto_estudiante` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_proyecto_integrante`, `id_proyecto_estudiante`, `id_integrante`),
  INDEX `fk_proyectos_estudiantes_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_proyectos_estudiantes_has_integrantes_proyectos_estudian_idx` (`id_proyecto_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_estudiantes_has_integrantes_proyectos_estudiantes1`
    FOREIGN KEY (`id_proyecto_estudiante`)
    REFERENCES `grupo-investigacion`.`proyectos_estudiantes` (`id_proyecto_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_estudiantes_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`proyectos_estudiantes_has_lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`proyectos_estudiantes_has_lineas` (
  `id_proyecto_linea` INT NOT NULL AUTO_INCREMENT,
  `id_proyecto_estudiante` INT NOT NULL,
  `id_linea` INT NOT NULL,
  PRIMARY KEY (`id_proyecto_linea`, `id_proyecto_estudiante`, `id_linea`),
  INDEX `fk_proyectos_estudiantes_has_lineas_lineas1_idx` (`id_linea` ASC) VISIBLE,
  INDEX `fk_proyectos_estudiantes_has_lineas_proyectos_estudiantes1_idx` (`id_proyecto_estudiante` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_estudiantes_has_lineas_proyectos_estudiantes1`
    FOREIGN KEY (`id_proyecto_estudiante`)
    REFERENCES `grupo-investigacion`.`proyectos_estudiantes` (`id_proyecto_estudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_estudiantes_has_lineas_lineas1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `grupo-investigacion`.`lineas` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`programas_educativos_has_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`programas_educativos_has_materias` (
  `id_programa_materia` INT NOT NULL AUTO_INCREMENT,
  `id_programa_educativo` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id_programa_materia`, `id_programa_educativo`, `id_materia`),
  INDEX `fk_programas_educativos_has_materias_materias1_idx` (`id_materia` ASC) VISIBLE,
  INDEX `fk_programas_educativos_has_materias_programas_educativos1_idx` (`id_programa_educativo` ASC) VISIBLE,
  CONSTRAINT `fk_programas_educativos_has_materias_programas_educativos1`
    FOREIGN KEY (`id_programa_educativo`)
    REFERENCES `grupo-investigacion`.`programas_educativos` (`id_programa_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programas_educativos_has_materias_materias1`
    FOREIGN KEY (`id_materia`)
    REFERENCES `grupo-investigacion`.`materias` (`id_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`dependencia_has_area_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`dependencia_has_area_academica` (
  `id_dependencia_area` INT NOT NULL AUTO_INCREMENT,
  `id_dependencia` INT NOT NULL,
  `id_area_academica` INT NOT NULL,
  PRIMARY KEY (`id_dependencia_area`, `id_dependencia`, `id_area_academica`),
  INDEX `fk_dependencia_has_area_academica_area_academica1_idx` (`id_area_academica` ASC) VISIBLE,
  INDEX `fk_dependencia_has_area_academica_dependencia1_idx` (`id_dependencia` ASC) VISIBLE,
  CONSTRAINT `fk_dependencia_has_area_academica_dependencia1`
    FOREIGN KEY (`id_dependencia`)
    REFERENCES `grupo-investigacion`.`dependencia` (`id_dependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dependencia_has_area_academica_area_academica1`
    FOREIGN KEY (`id_area_academica`)
    REFERENCES `grupo-investigacion`.`areas_academicas` (`id_area_academica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`tipos_gestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`tipos_gestion` (
  `id_tipo_gestion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_gestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`gestion_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`gestion_academica` (
  `id_gestion_academica` INT NOT NULL AUTO_INCREMENT,
  `responsabilidad` VARCHAR(255) NOT NULL,
  `funcion_encomendada` VARCHAR(255) NOT NULL,
  `id_tipo_gestion` INT NOT NULL,
  PRIMARY KEY (`id_gestion_academica`),
  INDEX `fk_Gestion_Academica_tipos_gestion1_idx` (`id_tipo_gestion` ASC) VISIBLE,
  CONSTRAINT `fk_Gestion_Academica_tipos_gestion1`
    FOREIGN KEY (`id_tipo_gestion`)
    REFERENCES `grupo-investigacion`.`tipos_gestion` (`id_tipo_gestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`gestion_academica_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`gestion_academica_has_integrantes` (
  `id_gestion_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_gestion_academica` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_gestion_integrante`, `id_gestion_academica`, `id_integrante`),
  INDEX `fk_Gestion_Academica_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_Gestion_Academica_has_integrantes_Gestion_Academica1_idx` (`id_gestion_academica` ASC) VISIBLE,
  CONSTRAINT `fk_Gestion_Academica_has_integrantes_Gestion_Academica1`
    FOREIGN KEY (`id_gestion_academica`)
    REFERENCES `grupo-investigacion`.`gestion_academica` (`id_gestion_academica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gestion_Academica_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`estancias_academicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`estancias_academicas` (
  `id_estancias_academicas` INT NOT NULL AUTO_INCREMENT,
  `institucion` VARCHAR(70) NOT NULL,
  `proposito` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `anios_id_anio` INT NOT NULL,
  PRIMARY KEY (`id_estancias_academicas`),
  INDEX `fk_estancias_academicas_anios1_idx` (`anios_id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_estancias_academicas_anios1`
    FOREIGN KEY (`anios_id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`estancias_academicas_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`estancias_academicas_has_integrantes` (
  `id_estancia_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_estancias_academicas` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_estancia_integrante`, `id_estancias_academicas`, `id_integrante`),
  INDEX `fk_estancias_academicas_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_estancias_academicas_has_integrantes_estancias_academica_idx` (`id_estancias_academicas` ASC) VISIBLE,
  CONSTRAINT `fk_estancias_academicas_has_integrantes_estancias_academicas1`
    FOREIGN KEY (`id_estancias_academicas`)
    REFERENCES `grupo-investigacion`.`estancias_academicas` (`id_estancias_academicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estancias_academicas_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`estancias_academicas_has_lineas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`estancias_academicas_has_lineas` (
  `id_estancia_linea` INT NOT NULL AUTO_INCREMENT,
  `id_estancias_academicas` INT NOT NULL,
  `id_linea` INT NOT NULL,
  PRIMARY KEY (`id_estancia_linea`, `id_estancias_academicas`, `id_linea`),
  INDEX `fk_estancias_academicas_has_lineas_lineas1_idx` (`id_linea` ASC) VISIBLE,
  INDEX `fk_estancias_academicas_has_lineas_estancias_academicas1_idx` (`id_estancias_academicas` ASC) VISIBLE,
  CONSTRAINT `fk_estancias_academicas_has_lineas_estancias_academicas1`
    FOREIGN KEY (`id_estancias_academicas`)
    REFERENCES `grupo-investigacion`.`estancias_academicas` (`id_estancias_academicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estancias_academicas_has_lineas_lineas1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `grupo-investigacion`.`lineas` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`reuniones_academicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`reuniones_academicas` (
  `id_reunion_academica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `periodicidad` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_reunion_academica`),
  INDEX `fk_reuniones_academicas_anios1_idx` (`id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_reuniones_academicas_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`reuniones_academicas_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`reuniones_academicas_has_integrantes` (
  `id_reunion_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_reunion_academica` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_reunion_integrante`, `id_reunion_academica`, `id_integrante`),
  INDEX `fk_reuniones_academicas_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_reuniones_academicas_has_integrantes_reuniones_academica_idx` (`id_reunion_academica` ASC) VISIBLE,
  CONSTRAINT `fk_reuniones_academicas_has_integrantes_reuniones_academicas1`
    FOREIGN KEY (`id_reunion_academica`)
    REFERENCES `grupo-investigacion`.`reuniones_academicas` (`id_reunion_academica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reuniones_academicas_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`tipo_participacion_ca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`tipo_participacion_ca` (
  `id_tipo_participacion_ca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_participacion_ca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`participaciones_ca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`participaciones_ca` (
  `id_participacion_ca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `id_tipo_participacion_ca` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `id_anio` INT NOT NULL,
  PRIMARY KEY (`id_participacion_ca`),
  INDEX `fk_participaciones_ca_tipo_participacion_ca1_idx` (`id_tipo_participacion_ca` ASC) VISIBLE,
  INDEX `fk_participaciones_ca_anios1_idx` (`id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_participaciones_ca_tipo_participacion_ca1`
    FOREIGN KEY (`id_tipo_participacion_ca`)
    REFERENCES `grupo-investigacion`.`tipo_participacion_ca` (`id_tipo_participacion_ca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participaciones_ca_anios1`
    FOREIGN KEY (`id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`participaciones_ca_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`participaciones_ca_has_integrantes` (
  `id_participacion_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_participacion_ca` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_participacion_integrante`, `id_participacion_ca`, `id_integrante`),
  INDEX `fk_participaciones_ca_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_participaciones_ca_has_integrantes_participaciones_ca1_idx` (`id_participacion_ca` ASC) VISIBLE,
  CONSTRAINT `fk_participaciones_ca_has_integrantes_participaciones_ca1`
    FOREIGN KEY (`id_participacion_ca`)
    REFERENCES `grupo-investigacion`.`participaciones_ca` (`id_participacion_ca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participaciones_ca_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actualizacion_pe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actualizacion_pe` (
  `id_actualizacion_pe` INT NOT NULL,
  `id_programa_educativo` INT NOT NULL,
  `fecha_implementacion` DATE NOT NULL,
  `anios_id_anio` INT NOT NULL,
  PRIMARY KEY (`id_actualizacion_pe`),
  INDEX `fk_actualizacion_pe_programas_educativos1_idx` (`id_programa_educativo` ASC) VISIBLE,
  INDEX `fk_actualizacion_pe_anios1_idx` (`anios_id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_actualizacion_pe_programas_educativos1`
    FOREIGN KEY (`id_programa_educativo`)
    REFERENCES `grupo-investigacion`.`programas_educativos` (`id_programa_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actualizacion_pe_anios1`
    FOREIGN KEY (`anios_id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actualizacion_pe_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actualizacion_pe_has_integrantes` (
  `id_actualizacion_integrante` INT NOT NULL AUTO_INCREMENT,
  `id_actualizacion_pe` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_actualizacion_integrante`, `id_actualizacion_pe`, `id_integrante`),
  INDEX `fk_actualizacion_pe_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_actualizacion_pe_has_integrantes_actualizacion_pe1_idx` (`id_actualizacion_pe` ASC) VISIBLE,
  CONSTRAINT `fk_actualizacion_pe_has_integrantes_actualizacion_pe1`
    FOREIGN KEY (`id_actualizacion_pe`)
    REFERENCES `grupo-investigacion`.`actualizacion_pe` (`id_actualizacion_pe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actualizacion_pe_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actualizacion_pg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actualizacion_pg` (
  `id_actualizacion_pg` INT NOT NULL AUTO_INCREMENT,
  `programas_educativos_id_programa_educativo` INT NOT NULL,
  `fecha_implementacion` DATE NOT NULL,
  `anios_id_anio` INT NOT NULL,
  PRIMARY KEY (`id_actualizacion_pg`),
  INDEX `fk_actualizacion_pg_programas_educativos1_idx` (`programas_educativos_id_programa_educativo` ASC) VISIBLE,
  INDEX `fk_actualizacion_pg_anios1_idx` (`anios_id_anio` ASC) VISIBLE,
  CONSTRAINT `fk_actualizacion_pg_programas_educativos1`
    FOREIGN KEY (`programas_educativos_id_programa_educativo`)
    REFERENCES `grupo-investigacion`.`programas_educativos` (`id_programa_educativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actualizacion_pg_anios1`
    FOREIGN KEY (`anios_id_anio`)
    REFERENCES `grupo-investigacion`.`anios` (`id_anio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`actualizacion_pg_has_integrantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`actualizacion_pg_has_integrantes` (
  `id_actualizacion_integrantes` INT NOT NULL AUTO_INCREMENT,
  `d_actualizacion_pg` INT NOT NULL,
  `id_integrante` INT NOT NULL,
  PRIMARY KEY (`id_actualizacion_integrantes`, `d_actualizacion_pg`, `id_integrante`),
  INDEX `fk_actualizacion_pg_has_integrantes_integrantes1_idx` (`id_integrante` ASC) VISIBLE,
  INDEX `fk_actualizacion_pg_has_integrantes_actualizacion_pg1_idx` (`d_actualizacion_pg` ASC) VISIBLE,
  CONSTRAINT `fk_actualizacion_pg_has_integrantes_actualizacion_pg1`
    FOREIGN KEY (`d_actualizacion_pg`)
    REFERENCES `grupo-investigacion`.`actualizacion_pg` (`id_actualizacion_pg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actualizacion_pg_has_integrantes_integrantes1`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `grupo-investigacion`.`integrantes` (`id_integrante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo-investigacion`.`objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo-investigacion`.`objetivos` (
  `id_objetivo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_objetivo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
